### ISSUE TITLE
relation-dropdown lists all the versions instead of just the latest ones 

### ISSUE THREAD

**Issue by kamil-malinski** [notum-cz/strapi-plugin-content-versioning#19]
### Describe the bug

When a collection (A) has a relation to versioned collection (B) the dropdown in the edit view lists all the entries of collection (B) instead of just the latest ones. In other words: the relation-dropdown doesn't respect the "is_visible_in_list_view"-flag.

### Steps to reproduce the behavior

1. Create a collection (B) and turn versioning on.
2. Create a few entries into collection B and create a few versions of each entry
3. Create another collection (A) and add a relation to collection (B).
4. Create an entry for collection (A) and open the collection (B) relation dropdown
5. All the versions of every entry are in the dropdown and not just the latest ones.

### Expected behavior

Only the latest versions of every entry of collection (B) should appear in the dropdown.

### System

- Node.js version: v14.18.3
- NPM version: 6.14.15
- Strapi version: 4.15.
- Database: MySQL
- Operating system: MacOS

**Comment by tasola** [comment]
@martincapek @kamil-malinski Have you tested this with more advanced cases than the one described above? I experience the same thing (I am aware that it is a known limitation), but I'm thinking we might be able to live with this behaviour - as long as there isn't any more issues than the one described in this issue. Are there any more known limitations to the relations specifically?

**Comment by tasola** [comment]
I tested some other scenarios. I guess it's already obvious for the ones familiar with the code base, but I still wanna write them here in case someone like me stumbles upon this thread later on.

* If you were to fetch (B) with the `populate=*` query param (to get (B):s relations), you would only get the published version (no other versions).
* All versions of (A) shown in (B):s relations dropdown seems to be consequently DESC sorted; the latest version being on top.
* If you were to delete one of the (A) relations in the dropdown, you will (of course) also lose the relation to this version in case it gets published again. I.e, if you have the relations a1, a2 and a3 (a3 being the current published version of (A)), and you would remove the a2 relation, that would leave you with two unpublished relations a1 and a3 in case you were to publish a2 instead of a3 later on.

The three points above are fairly easy to reason about. I haven't seen any behaviour that seems *totally* off, or any errors thrown or similar. I'm still interested in hearing if there are such known issues though.
