### ISSUE TITLE
TypeError: latestInLocales.rows is not iterable

### ISSUE THREAD

**Issue by andrew-hu368** [notum-cz/strapi-plugin-content-versioning#96]
### Describe the bug

A fresh Strapi with SQLite is not compatible with this plugin due to this error `TypeError: latestInLocales.rows is not iterable`.

The error seems to be on `core-api.js` file where `latestInLocales.rows` should be replaced with `latestInLocales`.

### Steps to reproduce the behavior

1. Bootstrap a new Strapi project
2. Downgrade to 4.11.4
3. Install `@notum-cz/strapi-plugin-content-versioning `

### System

- Node.js version: v16
- NPM version: 8.19.4
- Strapi version: 4.11.4
- Database: SQLite
- Operating system: MacOS Darwin

**Comment by omikulcik** [comment]
Hi @andrew-hu368, I was able to reproduce this issue. Unfortunately since we use raw queries SQLite and Postgres return different values. Our plan is to rewrite the queries using Knex which would solve this problem. I will try to think of a temporary solution.

For now, everywhere `latestInLocales.rows` is used it should work with just `latestInLocales.rows` for SQLite.

**Comment by Sklico** [comment]
@omikulcik I have the same problem with MySQL.
